# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

formats:
  - pdf
  - epub

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    pre_install:
      - python -m pip install pip-tools
      - pip-compile -o unifyfs-docs/requirements.txt unifyfs-docs/requirements.in
    post_install:
      - cat unifyfs-docs/requirements.txt
  # disabled in test-docs repo
  #  post_checkout:
  #    # Cancel building pull requests when there aren't changed in the docs directory or YAML file.
  #    - |
  #      if [ "$READTHEDOCS_VERSION_TYPE" = "external" ] && git diff --quiet origin/dev -- unifyfs-docs/ .readthedocs.yaml;
  #      then
  #        exit 183;
  #      fi

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: unifyfs-docs/docs/conf.py
  fail_on_warning: true

# We recommend specifying your dependencies to enable reproducible builds:
# https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html
python:
  install:
  - requirements: unifyfs-docs/requirements.txt
